language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
env:
  - DB=mysql
mysql -e "create database IF NOT EXISTS licapi;" -uroot; fi
script: phpunit --configuration phpunit_mysql.xml --coverage-text
